name: CI

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          cargo build
          cargo build --release
